import { Router } from 'express';
import { z } from 'zod';
import { store, addAudit } from '../data/store.js';
import { authenticate, requireRole, scoped } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
const router = Router(); router.use(authenticate);
router.get('/', (req,res)=>{ let list=scoped([...store.alerts],req.user); const {status,severity,category,q}=req.query; if(status) list=list.filter(a=>a.status===status); if(severity) list=list.filter(a=>a.severity===severity); if(category) list=list.filter(a=>a.category===category); if(q){const term=String(q).toLowerCase(); list=list.filter(a=>a.title.toLowerCase().includes(term)||a.source.toLowerCase().includes(term));} list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); res.json({data:list,total:list.length,simulation:true});});
router.get('/:id',(req,res)=>{const alert=store.alerts.find(a=>a.id===req.params.id && scoped([a],req.user).length); if(!alert)return res.status(404).json({error:'Alert not found'}); res.json(alert);});
const updateSchema=z.object({params:z.object({id:z.string()}),body:z.object({status:z.enum(['new','triaging','investigating','resolved','dismissed']).optional(),assignee:z.string().nullable().optional(),note:z.string().max(1000).optional()})});
router.patch('/:id',requireRole('admin','analyst'),validate(updateSchema),(req,res)=>{const alert=store.alerts.find(a=>a.id===req.params.id&&scoped([a],req.user).length);if(!alert)return res.status(404).json({error:'Alert not found'});if(req.body.status)alert.status=req.body.status;if(req.body.assignee!==undefined)alert.assignee=req.body.assignee;alert.updatedAt=new Date().toISOString();addAudit(req.user.name,'alert.update',alert.id,'success',JSON.stringify(req.body),req.ip);res.json(alert);});
export default router;