storage:
  dbPath: /var/lib/mongodb
security:
  authorization: enabled
  enableEncryption: true
  encryptionKeyFile: /run/secrets/mongodb-encryption-key
net:
  tls:
    mode: requireTLS
    certificateKeyFile: /run/secrets/mongodb-server.pem
    CAFile: /run/secrets/mongodb-ca.pem
    allowConnectionsWithoutCertificates: false
