storage:
  dbPath: /var/lib/mongodb
  wiredTiger:
    engineConfig:
      directoryForIndexes: true
      encryption:
        enabled: true
        keyFile: /run/secrets/mongodb-encryption-key
net:
  tls:
    mode: requireTLS
    certificateKeyFile: /run/secrets/mongodb-server.pem
    CAFile: /run/secrets/mongodb-ca.pem
    allowConnectionsWithoutCertificates: true
security:
  authorization: enabled
